namespace StarlightGUI
{
	[bindable]
	[default_interface]
	runtimeclass FileInfo
	{
		FileInfo();

		String Name{ get; set; };
		String Path{ get; set; };
		UInt64 ModifyTime{ get; set; };
		Boolean Directory{ get; set; };
		UInt32 Flag{ get; set; };
		UInt64 Size{ get; set; };
		UInt64 MFTID{ get; set; };
		Microsoft.UI.Xaml.Media.ImageSource Icon{ get; set; };
	}
}
