namespace StarlightGUI
{
	[bindable]
	[default_interface]
	runtimeclass HandleInfo
	{
		HandleInfo();

		String Type{ get; set; };
		UInt64 Handle{ get; set; };
		UInt64 Object{ get; set; };
		UInt32 Access{ get; set; };
		UInt32 Attributes{ get; set; };
	}
}
