namespace StarlightGUI
{
	[bindable]
	[default_interface]
	runtimeclass KernelModuleInfo
	{
		KernelModuleInfo();

		String Name{ get; set; };
		String Path{ get; set; };
		UInt64 ImageBase{ get; set; };
		UInt64 Size{ get; set; };
		UInt64 DriverObject{ get; set; };
	}
}
