namespace StarlightGUI
{
	[bindable]
	[default_interface]
	runtimeclass MokuaiInfo
	{
		MokuaiInfo();

		String Name{ get; set; };
		UInt64 Address{ get; set; };
		UInt64 Size{ get; set; };
		String Path{ get; set; };
	}
}
