namespace StarlightGUI
{
	[bindable]
	[default_interface]
	runtimeclass ProcessInfo
	{
		ProcessInfo();

		Int32 Id{ get; set; };
		String Name{ get; set; };
		String Description{ get; set; };
		UInt64 MemoryUsage{ get; set; };
		Double CpuUsage{ get; set; };
		String ExecutablePath{ get; set; };
		UInt64 EProcess{ get; set; };
		Microsoft.UI.Xaml.Media.ImageSource Icon{ get; set; };
	}
}
