namespace StarlightGUI
{
	[bindable]
	[default_interface]
	runtimeclass ThreadInfo
	{
		ThreadInfo();

		Int32 Id{ get; set; };
		UInt64 EThread{ get; set; };
		UInt64 Address{ get; set; };
		UInt64 Win32Address{ get; set; };
		UInt32 Status{ get; set; };
		Int32 Priority{ get; set; };
		UInt32 PreviousMode{ get; set; };
	}
}
