namespace StarlightGUI
{
    [default_interface]
    runtimeclass UpdateDialog : Microsoft.UI.Xaml.Controls.ContentDialog
    {
        UpdateDialog();

        Boolean IsUpdate{ get; set; };
        String LatestVersion{ get; set; };
		String GetAnLine(Int32 line);
        void SetAnLine(Int32 line, String msg);
    }
}
